# Generated by Django 3.2.23 on 2023-11-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user-placeholder.jpeg', upload_to='profile_pics'),
        ),
    ]
